In [1]:
import tensorflow as tf

In [30]:
cons = tf.constant([[1, 2., 3], [4, 5, 6.]])

In [7]:
cons

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [8]:
cons.shape

TensorShape([2, 3])

In [9]:
cons.dtype

tf.float32

In [11]:
cons[1, 1:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [12]:
cons+5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [13]:
tf.add(cons, 10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [17]:
tf.squeeze(cons)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [18]:
tf.transpose(cons)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [19]:
tf.keras.backend

<module 'keras.api._v2.keras.backend' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\keras\\api\\_v2\\keras\\backend\\__init__.py'>

In [21]:
from tensorflow import keras

In [22]:
k = keras.backend

In [23]:
k.transpose(cons) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 14.],
       [12., 15.],
       [13., 16.]], dtype=float32)>

In [24]:
cons.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [26]:
tf.constant(2.) + tf.constant(5.)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [27]:
tf.Tensor

tensorflow.python.framework.ops.Tensor

In [31]:
cons

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [33]:
cons_var = tf.Variable([[1, 2, 3], [4, 5, 6]])

In [34]:
cons_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

###### Custom Loss Functions

In [37]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

###### Custom metrics

In [40]:
prec = keras.metrics.Precision()

In [46]:
prec([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.93333334>

In [47]:
prec.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.93333334>

In [48]:
prec.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([14.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>]

###### Custom Layers

In [49]:
exp_layer = keras.layers.Lambda(lambda x: tf.exp(x))