In [1]:
import tensorflow as tf

In [2]:
cons = tf.constant([[1, 2., 3], [4, 5, 6.]])

In [3]:
cons

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
cons.shape

TensorShape([2, 3])

In [5]:
cons.dtype

tf.float32

In [6]:
cons[1, 1:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [7]:
cons+5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [8]:
tf.add(cons, 10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [9]:
tf.squeeze(cons)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [10]:
tf.transpose(cons)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [11]:
tf.keras.backend

<module 'keras.api._v2.keras.backend' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\keras\\api\\_v2\\keras\\backend\\__init__.py'>

In [12]:
from tensorflow import keras

In [13]:
k = keras.backend

In [14]:
k.transpose(cons) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 14.],
       [12., 15.],
       [13., 16.]], dtype=float32)>

In [15]:
cons.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [16]:
tf.constant(2.) + tf.constant(5.)

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [17]:
tf.Tensor

tensorflow.python.framework.ops.Tensor

In [18]:
cons

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [19]:
cons_var = tf.Variable([[1, 2, 3], [4, 5, 6]])

In [20]:
cons_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

###### Custom Loss Functions

In [21]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

###### Custom metrics

In [22]:
prec = keras.metrics.Precision()

In [23]:
prec([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [24]:
prec.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [25]:
prec.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>]

###### Custom Layers

In [26]:
exp_layer = keras.layers.Lambda(lambda x: tf.exp(x))

###### Functions

In [27]:
def cube(n):
    return n**3

In [28]:
cube(2)

8

In [30]:
cube(tf.constant(3.0))

<tf.Tensor: shape=(), dtype=float32, numpy=27.0>

In [31]:
tf_cube = tf.function(cube)
tf_cube

In [32]:
tf_cube(3)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [33]:
tf_cube(tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [34]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [36]:
import numpy as np
tf.constant(np.array(range(10)))

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

##### Data API

In [70]:
x = tf.range(10)

In [71]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [72]:
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [73]:
for i in dataset:
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [74]:
dataset = dataset.repeat(3).batch(10)

In [75]:
for i in dataset:
    print(i)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [76]:
dataset = dataset.apply(tf.data.experimental.unbatch())

In [78]:
for i in dataset:
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype